version: "3"

services:
    db:
        container_name: mongo_db
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: DB!2020
        ports:
            - "27018:27017"

        networks:
            - app-network
    api:
        container_name: API
        build: .
        command: node ./index.js
        environment:
            SERVER_PORT: 8082
            DB_URL: mongodb://db:27017
            DB_NAME: backend_app
            DB_PASS: DB!2020
            DB_USER: admin
        ports:
            - "8082:8082"
        networks:
            - app-network
        links:
            - db
        depends_on:
            - db

networks:
    app-network:
        driver: bridge
